openjdk.build/makefile
=> Add test.Custom target to openjdk.build/maklefile - issue #11

build.xml, openjdk.build/playlist.xml
Added top level build file to build all systemtest projects with
testKitGen. Also, added playlist.xml for svt tests 
=> Issue 5 : Integrate system test with testkitgen

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
This PR satisfies https://github.com/AdoptOpenJDK/JCK8/issues/4
tools.jar is added to the classpath when running these tests.
platform.os is now set to 'Current system' to use the same property names across all platforms.
Also includes
1. A fix to remove --add-modules for the javatest agent when running jck8 which was introduced by adding jck9 support.
2. A fix to space separate rather than ':' or ';' separate the list of JDK jars required as input to certain tests.
=> Enable jck8 live phase testing, simplify platform.os settings

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Fixes https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/20#pullrequestreview-71137775
=> Remove commented out code

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Fixes https://github.com/AdoptOpenJDK/JCK8/issues/5
=> Make the existence of a jck .kfl file optional

openjdk.build/include/top.xml, openjdk.build/makefile, openjdk.build/playlist.xml
=> Backport systemtest build debugging options to ci.adopt systemtest build

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Fixes https://github.com/AdoptOpenJDK/JCK8/issues/6
=> Fix settings overrides when top level JCK test nodes are executed

openjdk.build/makefile
Fixes https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/17
=> Add result root

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
=> Remove extraneous comma

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Fixes https://github.com/AdoptOpenJDK/JCK8/issues/8
=> Add -Djdk.attach.allowAttachSelf=true to test command lines

openjdk.test.jck/include/test_targets.mk, openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
=> Add interactive=yes option to test.jck and a makefile target to run it

openjdk.build/include/top.xml
=> Issue 19: Add more debug messages to systemtest build scripts

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
More fixes for https://github.com/AdoptOpenJDK/stf/issues/20
=> Fix for more osx fixes showing up later in JCK execution

openjdk.build/makefile
=> Set SHELL to cmd.exe on Windows

openjdk.test.math/src/test.math/net/adoptopenjdk/test/math/MathAPITest.java
=> Issue 76 : accept both IBM and Oracle result for MathApiTest

openjdk.test.math/src/test.math/net/adoptopenjdk/test/math/MathAPITest.java
=> Fix wrong test value

openjdk.build/build.xml
Include back commented out systemtests
=> Include back commented out systemtests

openjdk.test.modularity/build.xml
Fix modularity test compilation issue 
=> Fix Modularity test compilation issue

openjdk.test.jlm/.project, openjdk.test.modularity/.project
Fixes https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/115
=> Add .project files

openjdk.test.modularity/.classpath
Fixes https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/124
=> Add dummy .classpath file

openjdk.build/include/top.xml, openjdk.test.mauve/build.xml, openjdk.test.nio/src/test.nio/net/adoptopenjdk/test/nio2/perl/filesystems/generateProviders.pl
Fixes https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/127
=> Use curl to download systemtest prereqs when on zos

openjdk.build/include/top.xml
Removed ${} from referenced properties used as flags.
=> Removed ${} from referenced properties used as flags.

openjdk.build/include/top.xml
Fix description of download-file macro
=> Fix description of download-file macro

.gitattributes.zos, openjdk.build/include/top.xml, openjdk.test.classloading/build.xml, openjdk.test.concurrent/build.xml, openjdk.test.debugging/build.xml, openjdk.test.gc/build.xml, openjdk.test.jck/build.xml, openjdk.test.jlm/build.xml, openjdk.test.lambdasAndStreams/build.xml, openjdk.test.lang/build.xml, openjdk.test.load/build.xml, openjdk.test.locking/build.xml, openjdk.test.math/build.xml, openjdk.test.mauve/build.xml, openjdk.test.nio/build.xml, openjdk.test.serialization/build.xml, openjdk.test.util/build.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/139
=> Enable systemtest on z/OS

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Fixes https://github.com/AdoptOpenJDK/JCK/issues/5
=> Trim username retrieved from jcktest.properties

openjdk.test.mauve/build.xml
Resolves: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/155
=> Omit mauve classses that fail to compile on OpenJDK11 SDK

openjdk.test.jck/include/test_targets.mk
=> Fix missing = in test.jck.custom target

openjdk.build/build.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/171
=> Change JAVA_VERSION to JDK_VERSION

openjdk.test.mauve/build.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/173
=> Update JAVA_VERSION to JDK_VERSION in openjdk.test.mauve build.xml 

openjdk.test.jck/config/jck11/compiler.jti, openjdk.test.jck/config/jck11/devtools.jti, openjdk.test.jck/config/jck11/runtime.jti
java.transaction.xa and java.net.http are missing.
reviewer: @smlambert 
Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>
=> Update platform.module list for Java 11

openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/ClassHog.java, openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/ClassMapHog.java, openjdk.test.load/config/inventories/mauve/mauve_all.xml, openjdk.test.load/config/inventories/mauve/mauve_multiThread.xml, openjdk.test.mauve/build.xml
Remove mauve CORBA tests from building and running on all Java releases
=> Remove mauve CORBA tests from building and running on all Java releases

openjdk.test.load/config/inventories/mauve/mauve_all.xml, openjdk.test.load/config/inventories/mauve/mauve_multiThread.xml
Remove corba related tests from mauve test list
=> Remove corba related tests from mauve test list

openjdk.build/include/top.xml
Resolves: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/193 
=> Only attempt to use pre-staged mauve jar when it is available

openjdk.build/makefile
=> Changes to allow execution under cygwin

openjdk.test.modularity/src/tests/com.test/net/adoptopenjdk/test/modularity/junit/TestOverrideUsingPlatformModuleInRegularJar.java, openjdk.test.modularity/src/tests/com.test/net/adoptopenjdk/test/modularity/junit/TestOverrideUsingUpgradablePlatformModule.java
=> Fix call to getLocalPart()

openjdk.test.modularity/src/common-override/java.xml/javax/xml/namespace/QName.java
Related #201
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>
=> Convert QName.java to ASCII encoding and remove special character

openjdk.test.load/src/test.load/net/adoptopenjdk/stf/LambdaLoadTest.java
Increase timeout for LambdaLoadTest
=> Increase timeout for LambdaLoadTest

openjdk.build/build.xml, openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
Fixes https://github.com/eclipse/openj9-systemtest/issues/61
=> Fix modularity makefile for cygwin

openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
=> Add linux_arm-64 to native build

openjdk.test.load/src/test.load/net/adoptopenjdk/stf/ClassloadingLoadTest.java
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/227
=> Increase test timneout for classloading test

openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml, openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Disable gnu.testlet.java.net.DatagramSocket.bind
=> Disable gnu.testlet.java.net.DatagramSocket.bind

openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteClassAuth.java, openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteClassNoAuth.java, openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteMemoryAuth.java, openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteMemoryNoAuth.java, openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteNotifierProxyAuth.java, openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteThreadAuth.java, openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteThreadNoAuth.java
Increase workload on server process in JLM tests
=> Increase workload on server process in JLM tests

openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/PatchModuleImageTest.java
Increase timeout of subprocess in patch module image test
=> Increase timeout of subprocess in patch module image test

openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/256
=> Permanently exclude failing sub-test from mauve load test

openjdk.test.jck/config/jck13/compiler.jti, openjdk.test.jck/config/jck13/devtools.jti, openjdk.test.jck/config/jck13/runtime.jti
=> Add jck13 jti files

openjdk.test.debugging/.classpath, openjdk.test.debugging/build.xml, openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/stf/hcrAgent/HCRLateAttachWorkload.java
Related to : https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/261 
=> Update Reference of ASM 7.0 to 7.1

openjdk.build/build.xml, openjdk.test.mauve/build.xml
=> Add openjdk.test.mauve configure to openjdk.build

openjdk.test.jck/config/jck12/compiler.jti, openjdk.test.jck/config/jck12/runtime.jti, openjdk.test.jck/config/jck13/compiler.jti, openjdk.test.jck/config/jck13/runtime.jti, openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Resolves https://github.ibm.com/runtimes/test/issues/354
=> Add enable preview feature specific options for jck12 and jck13

openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml, openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/267
=> Permanently disable zipEntry subtests

openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml, openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/272
=> Permanently disable Mauve subtest gnu.testlet.java.lang.Math.sin

openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Related https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/271
=> Exclude sub-tests that use SecurityManager

openjdk.test.jck/build.xml, openjdk.test.jck/src/native/makefile, openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/279 
=> Enable JCK on Windows 

openjdk.build/build.xml
=> Add check to only build jck project in jck builds 

openjdk.test.modularity/build.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/286 
=> Update modularity build script with explicit gmake invocation for AIX

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
- Related to internal backlog issue # 149
- Restricts use of tnameserver in jck wrapper only within jck 8. tnameserver is a CORBA tool, it has been removed by http://openjdk.java.net/jeps/320
=> Restrict use of tnameserv to only jck8

openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MathLoadTest.java
This PR updates MathLoadTest to dynamically adjust to a lower load level if special JIT modes are being used. This will allow the MathLoadTests to run normally with special JIT modes and not time out. 
Related to: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/292
Related PRs: 
- https://github.com/eclipse/openj9-systemtest/pull/96
- https://github.com/AdoptOpenJDK/stf/pull/68
=> Dynamically adjust load for special slow running jvm options

openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveMultiThreadLoadTest.java
Related : https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/292
=> Use reduced load in Mauve multithreaded test for special JIT modes

openjdk.test.jck/config/jck14/compiler.jti, openjdk.test.jck/config/jck14/runtime.jti
Add JCK14 template configuration files
Internal test issues 370 
FYI @JasonFengJ9
=> Add JCK14 template configuration files

openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/298 
=> Exclude tests not suitable for multi-threaded testing

openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Related: https://github.com/eclipse/openj9/issues/7020
=> Exclude InputStreamReader.utf8 as invalid test

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/SummaryGenerator.java
- Adds missing copyright header
=> Add missing copyright header

.gitattributes.zos, openjdk.test.jck/src/native/makefile, openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>
=> JCK encoding fixes

openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml, openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
=> Exclude mauve DecimalFormat.setGroupingSize test

openjdk.test.debugging/.classpath, openjdk.test.debugging/build.xml, openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/stf/hcrAgent/HCRLateAttachWorkload.java
Upgrade ASM library to 7.3.1 to support SDK 15 
Related to : https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/333
=> Upgrade to ASM 7.3.1

openjdk.test.jck/config/jck15/compiler.jti, openjdk.test.jck/config/jck15/runtime.jti
- Add JCK15 template JTI files 
=> JTI files for JCK15

openjdk.test.jck/include/test_targets.mk, openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
=> Updates for JCK8c

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
=> Replace -release with -source for jck11+ versions

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>
=> zOS & AIX workaround for compRefExecute.fileSep OsHelper bug

openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveMultiThreadTestTrc.java, openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleThreadTestTrc.java
Related https://github.com/eclipse/openj9/issues/9982
=> Shorten Mauve test class names for special case with trace options

openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/JlinkTest.java
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/366
=> Fix jlink test for jdk16

openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/resources/ThreadData.java
Fixes https://github.com/eclipse/openj9/issues/1566
=> Fix jlmlocal and jlmthread tests

openjdk.test.load/src/test.load/net/adoptopenjdk/stf/DirectByteBufferLoadTest.java
=> Add think time to DirectByteBufferLoadTest

openjdk.test.mauve/build.xml
=> Use first path in prereqs root as mauve installation location

openjdk.build/build.xml, openjdk.test.jck/build.xml
=> Remove ant-contrib dependency

openjdk.test.jck/src/native/makefile, openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java, openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
Signed-off-by: Cheng Jin <jincheng@ca.ibm.com>
=> Add RISC-V support to the system test in OpenJDK

openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/AutoModTest.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/CLStressCRI.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/CLStressLayers.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/CLTestImage.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/CpMpModJar.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/CpMpModJar2.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/CpMpModJar3.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/ExplMod.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/InternalAPIs.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/JlinkPluginTest.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/JlinkTest.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/PatModImgTest.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/PatModTest.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/SLTest.java, openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/UpgModPathTest.java
Related to https://github.com/eclipse/openj9/issues/11365
=> Shorten modularity test names to suit Windows MAX_PATH limit

openjdk.test.load/config/inventories/mauve/mauve_all.xml, openjdk.test.load/config/inventories/mauve/mauve_multiThread.xml
=> Exclude mauve strictfp_modifier and Math.cos tests

openjdk.test.debugging/build.xml
Resolves: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/405
=> Remove dependency of ant-contrib <if> tag from openjdk.test.debugging project 

openjdk.test.debugging/.classpath, openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/stf/hcrAgent/HCRLateAttachWorkload.java, openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/StringModifierAgent.java
=> Allow more time for agent threads to terminate in HCRLateAttachWorkload

openjdk.test.jck/config/jck17/compiler.jti, openjdk.test.jck/config/jck17/runtime.jti
=> Add JCK17 configuration files

openjdk.test.mauve/build.xml
Resolves https://github.com/AdoptOpenJDK/run-aqa/issues/73
=> Update netbeans cvsclient.jar location

openjdk.test.jck/src/native/makefile
=> Stop deleting systemInfo and jmxlibid generated libraries

openjdk.test.jck/src/native/makefile, openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
fixes: https://github.com/adoptium/aqa-systemtest/issues/429
=> Use Sun Studio to compile on Solaris

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
=> Enable api/signaturetest to run on MacOS with no display

openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
jck api/javax_net tests TLS1.0 & 1.1 so must be enabled to support those tests.
=> Use custom security.properties for SSL TLS1.0,1.1

openjdk.test.jck/src/native/makefile, openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
After a number of iterations this version looks to have worked and is allowing the corresponding native modules to be built, therefore I believe this is good to merge 👍🏻
=> Windows tck natives fudge

openjdk.test.jck/config/default/jcktest.properties
I was getting some timeouts with TRSS. CI seems more stable
=> Switch testhost1name from trss to ci

openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
Fix #464 
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>
=> Update compiling natives macOS arm64 for jlink tests

openjdk.test.modularity/src/tests/com.test/net/adoptopenjdk/test/modularity/junit/TestLayers.java
Issue https://github.com/eclipse-openj9/openj9/issues/19242
Tested via grinder in https://github.com/eclipse-openj9/openj9/issues/19242#issuecomment-2032634859
=> Add more GC's to TestLayers
