- openjdk.build/makefile
When ant is installed via homebrew on OSX the ant-launcher.jar file ends up in /libexec/lib not /lib
> Support ant installation via homebrew on OSX

- openjdk.build/makefile
- openjdk.test.jck/config/jck9/compiler.jti
- openjdk.test.jck/config/jck9/devtools.jti
- openjdk.test.jck/config/jck9/runtime.jti
- openjdk.test.jck/include/test_targets.mk
- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Tests are running OK on VB Ubuntu and Windows 7.
There may be follow on changes as additional platforms are tested or if test suite changes.
> Add jck9 support to test.jck

- openjdk.test.jck/include/test_targets.mk
> Fix setting of JCKx_TESTS_NO_CONFIG macros

- openjdk.build/include/top.xml
Running build configure throws a malformed encoding exception
if there is "\u" character appearing in the PATH on Windows.
This fix resolves the issue by changing the single "\" to "\\"
in the generated file.
Fixes: #23
Signed-off-by: sabkrish <sabkrish@in.ibm.com>
> Fix for Malformed \uxxxx encoding error during make configure

- openjdk.test.jck/docs/README.md
Removing "executiontype" and "withagent" under the section ""Executing the
JCK tests via 'stf.pl'" in README.md doc of openjdk.test.jck and adding
"executiontype: The stf automation runs tests in multijvm way".
> JCK read me update issue#36

- openjdk.build/makefile
If the user wants to use stf.pl options that we don't anticipate in
the makefile, this option allows them to do that. This prevents code
duplication and dependencies between the make and perl code.
Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>
>  Allow users to pass arguments to the stf perl layer

- openjdk.test.jck/config/jck9/runtime.jti
This directive is already in the corresponding jti file for JCK8b and also in the other jti files for JCK9. For unknown reasons it's causing an error on my systems, but not on @lumpfish 's VM. It seems logical to have it synchronised with the others, therefore I'm adding it as it removes an issue and allows the suites to run.
> Add ExcludeListType to jck9/runtime.jti to sync with others

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Jck.java requires getOsgiOperatingSystemName() to return something useful. On macos it doesn't. This fix (along with an equivalent one to fix that method in the stf repository) will resolve this.
Fixes https://github.com/AdoptOpenJDK/stf/issues/20
> Fix osx support for JCK runs

- openjdk.build/makefile
Needed to be able to store full logs for JCK runs (and useful in other scenarios). Fixes https://github.com/AdoptOpenJDK/stf/issues/22
> Add stf RETAIN and RETAIN_LIMIT variables to makefile

- openjdk.build/include/top.xml
This may not be a great idea and may not be complete, but should work as an initial tactical fix for running the JCK
> Detect aarch64 in the arch string as arm

- openjdk.test.jck/src/native/makefile
Currently requires linux_ppc-64 to be specified, then you have to rename it to run the JCK. Which is clearly ridiculous. This fixes that
> Allow JCK native makefile to take linux_ppcle-64 as a PLATFORM

- openjdk.test.math/src/test.math/net/adoptopenjdk/test/math/MathAPITest.java
> Accept both Oracle and IBM values for toRadians(double)[0] test in MathAPITest

- openjdk.test.math/src/test.math/net/adoptopenjdk/test/math/MathAPITest.java
> Accept both Oracle and IBM value for double(1) which fails on OpenJDK10

- openjdk.test.math/src/test.math/net/adoptopenjdk/test/math/MathAPITest.java
We need to update the validation value for double(1) test from 200 to 500, as the value originally was 500.
> Fix test validation value for double(1)

- openjdk.test.math/src/test.math/net/adoptopenjdk/test/math/MathAPITest.java
Accept both Oracle and IBM values for (double)[2], (double)[3], (double)[4], (double)[5] tests as they are within one ULP of the acceptable value.
> Accept both Oracle and IBM value for toRadians(double) test

- openjdk.test.jck/config/jck10/compiler.jti
- openjdk.test.jck/config/jck10/devtools.jti
- openjdk.test.jck/config/jck10/runtime.jti
- openjdk.test.jck/src/native/makefile
Oracle appear to have switched the "generic UNIX" header file directory name from solaris to linux. While we could get more creative than this, the simplest solution would appear to be to let the makefile search in both locations, so that's what I've implemented. Partially fixes https://github.com/AdoptOpenJDK/stf/issues/35
> Update makefile to tolerate both jck8b and jck10 header file locations

- openjdk.test.jck/config/jck10/compiler.jti
- openjdk.test.jck/config/jck10/devtools.jti
- openjdk.test.jck/config/jck10/runtime.jti
- openjdk.test.jck/docs/README.md
- openjdk.test.jck/include/test_targets.mk
- openjdk.test.jck/src/native/makefile
- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Fixes https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/93
Fixes https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/92
Fixes https://github.com/AdoptOpenJDK/JCK10/issues/2
I've run some of the tests from each of the devtools, runtime and compiler jck10 test suites locally on a linux_x86-64 Ubuntu 16.04.  The only failure I've seen does not appear to relate to the automation.
I've also run the vm.jni and vm.jvmti tests which I think are the ones which run the native test cases - they passed.
Integrating this code should enable full runs to be done on the AdoptOpenJDK test machines
> Jdk10 support

- openjdk.test.modularity/build.xml
Update modularity test build script to use javac -h when on jdk10
> Update modularity test build script to use javac -h when on jdk10

- openjdk.test.modularity/build.xml
Remove ant-contrib depdendency from openjdk.modularity.test build file
> Remove ant-contrib depdendency from openjdk.modularity.test build file

- openjdk.test.modularity/build.xml
- openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/JlinkPluginOptionsTest.java
- openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/JlinkTest.java
Remove Java version number from native lib path for jlink test 
> Remove Java version number from native lib path for jlink test

- openjdk.build/makefile
Add make targets for Java 9 modularity tests
> Add make targets for Java 9 modularity tests and openjdk specific jlm tests 

- openjdk.build/makefile
Add missing test option for AutomaticModulesTest in makefile
> Add missing test option for AutomaticModulesTest

- openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
Add osx_x86-64 to list of supported platforms for modularity native tests
> Add osx_x86-64 to list of supported platforms

- openjdk.build/include/top.xml
Fixes: https://github.com/eclipse/openj9-systemtest/issues/29
> Update <get-platform-arch> macro for ppc64le platform

- openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/ServiceLoadersTest.java
Exclude failing sercice loaders tests until https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/137 is resolved
> Openjdk systemtest issue28

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Add `-Xmx2G` for `OpenJ9` to trigger an expected `OOM`
`-Xmx2G` is added for `OpenJ9` to trigger an expected `OOM` at `api/java_awt/Image_pack/WritableRaster/index.html#CreatePackedRasterTest1`, otherwise `OpenJ9` has default larger heap size in certain scenarios, no `OOM` and fails the test.
Reviewer: @smlambert 
FYI: @DanHeidinga
> Add -Xmx2G for OpenJ9 to trigger an expected OOM

- openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/UpgradeModPathTest.java
Resolves https://github.com/eclipse/openj9/issues/2389#issuecomment-405020193
> Increase timeout duration of concat process to avoid occasional timeout 

- openjdk.build/build.xml
- openjdk.test.mauve/build.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/148
> Update systemtest to build on Java 11

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Remove hard-coded `-Xmx2G`
Latest investigation shows the original `JCK` failure can be addressed without this hard-coded command line option;
This option also reserves the virtual address which might not be required, and causes `OOM` in certain scenarios.
Reviewer: @smlambert
FYI: @lumpfish @DanHeidinga
> Remove hardcoded -Xmx2G

- openjdk.test.jck/include/test_targets.mk
Restores concurrency=1 for tests which failed with concurrency=cpus+1 on Windows - see https://github.com/AdoptOpenJDK/JCK/issues/3
> Restore concurrency 1

- openjdk.test.jck/include/test_targets.mk
Part one of addressing https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/149.
The PR creates test.jck.xxx targets but does not remove the test.jck8b.xxx, test.jck9.xxx targets.  They will be removed in a different PR when all the Jenkins jobs running the old targets have been switched / replaced.
This does not affect tests being run via the test.jck.custom target.
New targets have been created to enable the runtime, compiler and devtools tests to be run separately (but via a single target), which will enable in particular running the runtime tests more frequently than the compiler and devtools tests.
> Reduce jck makefile targets

- openjdk.build/include/top.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/160
> Add arm to supported os.arch property values for arm32 platforms

- openjdk.test.jck/config/jck11/compiler.jti
- openjdk.test.jck/config/jck11/devtools.jti
- openjdk.test.jck/config/jck11/runtime.jti
- openjdk.test.jck/include/test_targets.mk
- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Enable `JCK11` test
Initial addition to run `JCK11` tests based on `JCK10` setup.
Manually verified that `make _jck-runtime-api-java_lang-String` and `make _jck-runtime-custom  JCK_TEST_TARGET=api/java_math` are working.
Related to https://github.com/AdoptOpenJDK/openjdk-tests/pull/507
Reviewer @smlambert 
FYI: @DanHeidinga @pshipton @llxia 
> Enable JCK11 test

- openjdk.test.jck/include/test_targets.mk
Needed to make sure we only validate JCKVERSION if a test.jck.xxx target is being run - otherwise make build commands failed because JCKVERSION was not set.
> Fix JCKVERSION validation

- openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/ClassHog.java
- openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/ClassMapHog.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/ClassloadingLoadTest.java
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/169
> Skip using javax.transaction.* and CORBA classes  for load test while on Java 11 and up

- openjdk.build/include/top.xml
Resolves: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/187
> Use prebuilt mauve.jar in automated systemtest builds

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Installation path of RPM/DEB may contain "lib" prefix.
runtime/compiler.api.signaturetest scan the lib path to get jars.
this is for issue #205
> Correct the lib path for the RPM-installed JREs

- openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
Add space after -o (output dir) in modularity native makefile
Signed-off-by: Mesbah_Alam@ca.ibm.com
> Add space after -o (output dir) in modularity native makefile

- openjdk.test.modularity/src/tests/com.test/net/adoptopenjdk/test/modularity/junit/TestStressLayers.java
Remove UTF characters from test class that causes compilation failure
> Remove UTF characters from test class that causes compilation failure

- openjdk.build/build.xml
Temporarily exclude modularity tests from building on Windows
> Temporarily exclude modularity tests from building on Windows

- openjdk.build/build.xml
Resolves : https://github.com/eclipse/openj9-systemtest/issues/66
> Fix logic in modularity test exclude for windows or jdk 8 only

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/LambdaLoadTest.java
Sets an inactivity limit of 60m for LambdaLoadTest
> Parameterize inactivityLimit for LambdaLoadTest

- openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
Add space after -o option in JlinkTest makefile
> Add space after -o option in JlinkTest makefile

- openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
Reverts AdoptOpenJDK/openjdk-systemtest#220 
It appears to be the cause of native tests failing to compile on Windows, https://github.com/eclipse/openj9-systemtest/issues/81).
> Revert "Add space after -o option in JlinkTest makefile"

- openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
Fixes https://github.com/eclipse/openj9-systemtest/issues/81
Signed-off-by: Mesbah_Alam@ca.ibm.com Mesbah_Alam@ca.ibm.com
> Add space after -o only while on osx

- openjdk.test.jck/config/jck12/compiler.jti
- openjdk.test.jck/config/jck12/devtools.jti
- openjdk.test.jck/config/jck12/runtime.jti
`JCK12` add `jti` files
Adding `JCK12` `compiler.jti`, `devtools.jti`, `runtime.jti` files.
Copied from `JCK11` folder and made modification accordingly.
Reviewer: @smlambert 
FYI: @DanHeidinga @pshipton
> JCK12 add jti files

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/237
> Add sub-test level excludes for failing mauve tests

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Disable failing gnu.testlet.java.text.MessageFormat.format14 and gnu.testlet.java.lang.System.arraycopy tests
> Disable failing mauve subtests:java.text.MessageFormat.format14, java.lang.System.arraycopy

- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Exclude security related tests from multithreaded mauve load
> Exclude security related tests from multithreaded mauve load

- openjdk.build/include/top.xml
- openjdk.test.debugging/.classpath
- openjdk.test.debugging/build.xml
- openjdk.test.debugging/docs/HCR_README.md
- openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/stf/hcrAgent/HCRLateAttachWorkload.java
- openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/MyClassVisitor.java
- openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/MyMethodVisitor.java
The HCRLateAttachWorkload test won't run on JDK11 if we're not using
ASM 7.0 or up.
This change updates the version of ASM from 5.2 to 7, and also removes
the 6-beta option, as 7 supersedes both.
Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>
> Update ASM 5.2 to 7.0 to support JDK11+

- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmGCMXBeanNotifier.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteClassAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteClassNoAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteMemoryAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteMemoryNoAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteNotifierProxyAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteThreadAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteThreadNoAuth.java
resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/249
igned-off-by: Mesbah_Alam@ca.ibm.com <Mesbah_Alam@ca.ibm.com>
> Add -Xmx256m to JLM test processes, decrease thread limit in server load

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Related to https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/263
> Permanently exclude testlet.javax.net.ssl.SSLContext.TestDefaultInit

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/260
> Permanently exclude Handler.isLoggable as it fails on jdk13

- openjdk.test.jck/src/native/makefile
JCk13 b09 update introduced some classes which require a source directory to be in the path. This PR fixes it. Details in internal issue. 
> Update PATH for JCK13 native compilation

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Fix relative path for jck excludes
> Fix relative path for jck excludes

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveMultiThreadLoadTest.java
We need to increase timeout of this test especially for Windows runs with special modes (e.g. Mode610-OSRG) where it takes longer than usual time to complete. 
> Increase Mauve Multithreaded load test timeout

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Related to : https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/284
Ref: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/284#issuecomment-527588341
Background: We were previously excluding all mauve sub-tests where we were seeing AccessControlException for security manager. This was the a wrong approach. What we need is to identify the sub-tests that install SecurityManager and exclude them. 
The way we have since identified the tests that install a SecurityManager is 
- Run grinders for multi-threaded mauve tests with following extra option: 
`-Xtrace:iprint=mt,trigger=method{java/lang/System.setSecurityManager*,jstacktrace} `
- Search for `.install` and exclude the sub-test that installs security manager. 
This PR un-excludes the previously excluded sub-tests, and …
> Resurrect mauve sub-test excludes for SecurityManager issues

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
**Remove obsoleted modules for JDK11+**
Modules `java.xml.ws` & `java.corba` have been removed from `JDK11+`.
Only add them for `JCK 9/10`.
`JDK8` doesn't support modules.
`--add-modules java.xml.ws,java.corba` can't be added for `JDK11+`, otherwise `javatest agent` can't start with following exception hence the `test harness` just failed with `Error accessing agent: java.net.ConnectException: Connection refused (Connection refused)`.
```
java.lang.module.FindException: Module java.xml.ws not found
at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
at java.base/java.lang.module.Resolver.resolve(Resolver.java:128)
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:304)
```
Verified in a local run that `JDK11` passed JCK sub-test `vm/jdwp`. …
> Remove obsoleted modules for JDK11+

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MathLoadTest.java
- Related to https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/292
- Reduces worklaod to MathLoadTest BigDecimal when following JIT options are used: `-Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve`, `Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation`, 
> Reduce workload of bigdecimal test

- openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
* Recognise bsd_x86-64 as a valid platform
* Set up make variables to work on bsd_x86-64
* FreeBSD and OpenBSD have both switched to Clang as default and don't have gcc
* NetBSD, I believe, still has gcc as default, but 'cc' will still work
* The include file path jni_md.h uses the full OS name, e.g. 'freebsd', rather than just 'bsd'.
* Other setup mirrors Linux for the most part
Note that other architectures are possible here (e.g., bsd_x86-32), but are not included in this change.
> Add support for BSD/amd64

- openjdk.test.classloading/build.xml
- openjdk.test.concurrent/build.xml
- openjdk.test.debugging/build.xml
- openjdk.test.gc/build.xml
- openjdk.test.jck/build.xml
- openjdk.test.jlm/build.xml
- openjdk.test.lambdasAndStreams/build.xml
- openjdk.test.lang/build.xml
- openjdk.test.load/build.xml
- openjdk.test.locking/build.xml
- openjdk.test.math/build.xml
- openjdk.test.mauve/build.xml
- openjdk.test.nio/build.xml
- openjdk.test.nio/src/test.nio/net/adoptopenjdk/test/nio2/perl/filesystems/generateProviders.pl
- openjdk.test.serialization/build.xml
- openjdk.test.util/build.xml
This reverts commit 65e79edbe3a365ac0b7fcecb8126ace8f6a39c28.
> Revert "Use encoding ISO-8859-1 for compiling system tests"

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/ClassloadingLoadTest.java
- Reduces workload to half of normal when special slow running JIT modes are used 
Resolves: https://github.com/eclipse/openj9-systemtest/issues/104
> Reduce workload on ClassLoadingLoadTest if special JIT options are used

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Update JCK STF wrapper to produce XML style JCK reports - to be consumed by xunit plugin in Jenkins so that we can produce Junit style test results. 
> Update JCK STF wrapper to produce XML style JCK reports 

- openjdk.test.jck/config/jck11/runtime.jti
- openjdk.test.jck/config/jck13/runtime.jti
- openjdk.test.jck/config/jck8b/compiler.jti
- openjdk.test.jck/config/jck8b/devtools.jti
- openjdk.test.jck/config/jck8b/runtime.jti
- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
**Disable ftpSupport temporarily**
Aim for a green `jck.extended` build.
Should be re-enabled when ftp server is setup properly.
Current `ftp` test failures:
```
----------out1:(6/368)----------
URL2022: Failed. Unexpected exception:java.net.ConnectException: Connection timed out (Connection timed out)
URL2024: Failed. Unexpected exception:java.net.ConnectException: Connection timed out (Connection timed out)
URL2023: Passed. OKAY
URL2026: Passed. OKAY
URL2025: Passed. OKAY
STATUS:Failed.test cases: 5; passed: 3; failed: 2; first test case failure: URL2022
```
With this PR, the test suite passes with following output:
```
----------out1:(6/246)----------
URL2022: Passed. Testcase skipped since ftp protocol is not supported
URL2024: Passed. Testcase skipped since ftp protocol is not …
```
> Disable ftpSupport temporarily

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/SummaryGenerator.java
- Adds a XML parser to process XML report and generate a Result Summary containing the list of test sand their passed/failed status -- exactly as the one that gets generated when we select HTML as the jck report type. We need this since we need to keep XML as our jck report type, and still would want the result summary in console. More background here: /backlog/issues/187 
> Output JCK test result summary

- openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/StringModifierAgent.java
- Increase threadsTimeout for transformer threads to finish - to resolve for intermittent failures. 
> Increase threadsTimeout for transformer threads to finish

- openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/ClassHog.java
- openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/ClassMapHog.java
- Skips using classes from java.security.acl  package in JDK14 for classloading load tests as that package no longer exists in JDK14. 
- Resolves https://github.com/eclipse/openj9/issues/8088
> Skip using classes from java.security.acl package on Java 14

- openjdk.test.debugging/.classpath
- openjdk.test.debugging/build.xml
- openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/stf/hcrAgent/HCRLateAttachWorkload.java
- Update ASM references for 7.3 
- Update openjdk.test.debugging build file to add extra options (--enable-preview, -source)  when compiling on jdk11, and up (note JDK 8 doesn't support --enable-preview)
- Related to : https://github.com/eclipse/openj9/issues/8085
> Update asm to 7.3

- openjdk.test.jck/build.xml
After https://github.com/AdoptOpenJDK/TKG/pull/30 - we no longer run TKG before compilation in which the map between SPEC --> PLATFORM used to be run. Hence we do not have `PLATFORM` variable available during compilation any more. This PR updates JCK build script to not depend on `PLATFORM`. 
This PR uses `java_platform` (initialized in in top.xml) in place of `PLATFORM` - which servers the same purpose. We already use it in the compilation of modularity test natives. 
Related: backlog/issues/231
> Use java_platform instead of PLATFORM in JCK build script

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleInvocationLoadTest.java
Exclude for https://github.com/eclipse/openj9/issues/8086
https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/322  missed similar exclude for the Single thread invocation variant of the Mauve load test - this PR adds it. 
> Exclude Mauve sub-test DecimalFormat.setGroupingSize from jdk 14 openj9 for Single thread invocation variation of mauve test

- openjdk.test.jck/src/native/makefile
- Add escape back-slash processing & forward slash processing for Cygwin for parts of cpaths that were missing it 
- Add quotes around paths that were missing them 
The above solves the windows JCK compilation failure that got introduced on JCK 11
Related : backlog/issues/169
> Fix Windows paths for cygwin in JCK makefile

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveMultiThreadLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleInvocationLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleThreadLoadTest.java
- Exclude for https://github.com/eclipse/openj9/issues/8620
> Exclude DecimalFormat.setGroupingSize from openj9 jdk15

- openjdk.build/makefile
- openjdk.test.load/config/inventories/mix/mix-more.xml
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MixedLoadTest.java
1) Created a inventory file called mix-few.xml, which contains below workloads.
bigdecimal
mauve_all
lang
nio
concurrent
2) Created a STF equivalent testcase MixedLoadTest.
3) Added MixedLoadTest to openjdk-tests otherLoadTests playlist.
> Adding mixed workloads to run as part of Load_Level_4

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
**jck11 requires -source 11 instead of -source 9**
This is expected to fix following error.
```
warning: as of release 10, 'var' is a restricted local variable type and cannot be used for type declarations or as the element type of an array
SAM s = (var i) -> i;
^
../tests/lang/LMBD/lmbd182/lmbd18201m001/lmbd18201m001.java:21: error: cannot find symbol
SAM s = (var i) -> i;
^
symbol:   class var
Number of errors: 1
```
Just added `jck11` case and didn't modified existing `jck9` just in case it is need for whatever reason. Assuming `jck10` is outdated.
Reviewer: @smlambert 
> jck11 requires -source 11 instead of -source 9

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
-Xdump:system:none is not a supported JVM option non Mac.
Resolves https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/339
> Do not use Xdump:system:none on osx as it's unsupported

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Add --enable-preview for jck 11+ programmatically 
> Add --enable-preview for jck 11+ programmatically

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Resolves https://github.ibm.com/runtimes/backlog/issues/284
> Remove check for osx when using dump optioons

- openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
- Add compiler flags and options for linux ppc 32 bit platform to modularity native build script
- Resolves https://github.ibm.com/runtimes/backlog/issues/308
> Add compiler coptions for linux ppc 32 bit platform to modularity native build script

- openjdk.test.jck/src/native/makefile
- openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
Add linux_390-32 and zos_390-32 to the list of supported platforms in test build script.
Background: backlog/issues/307
FYI @lumpfish 
> Add linux_390-32 and zos_390-32 to supported list of PLATFORMS

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveMultiThreadLoadTestWithTraceOption.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleThreadLoadTestWithTraceOption.java
- Adds two STF test classes to run Mauve single threaded and multi-threaded load tests on OpenJ9 only.
Related to https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/352#issuecomment-647733647 
> Add -Xdump option permanently to Mauve tests

- openjdk.test.jck/src/native/makefile
Resolves https://github.ibm.com/runtimes/backlog/issues/339
> Add -m32 gcc flag to linux 32 bit platforms

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveMultiThreadTestTrc.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleThreadTestTrc.java
- Add xdump options to mauve tests for MauveTestFailureException
- Related to https://github.com/AdoptOpenJDK/stf/issues/81
> Add xdump options to mauve tests for MauveTestFailureException

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveMultiThreadTestTrc.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleThreadTestTrc.java
- Fix reference of MauveTestFailureException in accordance with the change in https://github.com/AdoptOpenJDK/stf/pull/83/files#diff-ad5f317c88f122ae7ecf2be60b18f61e
> Update reference of MauveTestFailureException

- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
- Exclude tests that invoke TimeZone.setDefault()
- Background: https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/352#issuecomment-662144567
> Exclude tests that invoke TimeZone.setDefault()

- openjdk.test.load/config/inventories/util/util_exclude.xml
This test fails as per the referenced issue. Excluding the
test for now to make triage faster.
Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>
> Exclude SolverTest

- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteClassAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteClassNoAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteMemoryAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteMemoryNoAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteNotifierProxyAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteThreadAuth.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/TestJlmRemoteThreadNoAuth.java
> Adjust jlm load parameters

- openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/StringTransformer.java
If a class is defined after an instance of StringTransformer is registered,
the transform method will be called and passed a null className as the new
class is being defined. This will throw an exception and end the test so we
need to ensure the className is not null before the equality check.
Signed-off-by: Mike Zhang <mike.h.zhang@ibm.com>
Fixes https://github.com/eclipse/openj9/issues/10504
> Add null check to StringTransformer

- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/remote/ServerConnector.java
> Timeout jlm server connection using elapsed time and nbr attempts

- openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
> Fix osx native build

- openjdk.test.gc/src/test.gc/net/adoptopenjdk/test/gc/directbytebuffer/DirectMemoryTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/DirectByteBufferLoadTest.java
- Related to https://github.com/eclipse/openj9/issues/11112
> Add System.gc() calls to allow native memory to be reclaimed

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Exclude Mauve[gnu.testlet.java.lang.NullPointerException.constructor]
related: https://github.com/eclipse/openj9/issues/11206
> Exclude Mauve[gnu.testlet.java.lang.NullPointerException.constructor]

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Enable Mauve[gnu.testlet.java.lang.NullPointerException.constructor]
related https://github.com/eclipse/openj9/issues/11206
> Enable Mauve[gnu.testlet.java.lang.NullPointerException.constructor]

- openjdk.build/makefile
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MixedLoadTest.java
- Adds a time-based STF system test
Related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/2104
FYI @lumpfish 
> Add a time-based STF system test

- openjdk.test.debugging/.classpath
- openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/stf/hcrAgent/HCRLateAttachWorkload.java
- Update HCRLateAttachWorkload to use ASM 9.0
- Resolves failure in HCRLateAttachWorkload reported in https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/386
Related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/2125 + https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/386 
> Update ASM reference in HCRLateAttachWorkload to 9.0

- openjdk.test.load/config/inventories/mix/mix-more.xml
MiniMix load test runs [mix-more.xml ](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mix/mix-more.xml) load inventory using more than 1 thread. 
mix-more.xml runs [mauve_all.xml](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mix/mix-more.xml#L8) load. 
However, all exclusions for mauve multi-threaded scenario are in  [mauve_multiThread.xml](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/config/inventories/mauve/mauve_multiThread.xml). 
This may end up running mauve sub-tests which should not be run in multi-threaded scenario, e.g. tests that enable SecurityManager. 
This PR updates mix-more.xml configuration by specifying `mauve_multiThread.xml` to …
> Use mauve_multiThread load in mix-more load configuration

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
- Exclude sub-test incompatible with jdk16+ HotSpot to allow MiniMix system test to work on HotSpot JDk16+
- Related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/2150
> Exclude sub-test incompatible with jdk16+ HotSpot

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MathLoadTest.java
This PR reduces the 'math' variant of math load test's timeout value from `20h` to `2h`- which is a more practical timeout value. This prevents cases like the one reported [here](https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/389#issuecomment-756862024) where the test took more than 5 hours to complete. 
Related to https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/389
> Set timeout of sub-test to a reasonable value

- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/ClassloadingLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MathLoadTest.java
- The logic of how the tests figure out when slow running JIT modes are in effect has been modified. Now the test will treat any JIT option that contains `-Xjit:count` or `Xjit:enableOSR` (e.g. Mode614, Modew553, etc and the OSR modes) as slow running options and use a reduced workload. This will now ensure we do not run the "regular" (longer) load when any of these JIT modes are in use.
- Related to https://github.com/eclipse/openj9/issues/11666
> Have a reduced workload in MathLoadTest and ClassLoadinngLoadTest for all slow running JIT options

- openjdk.test.classloading/.classpath
- openjdk.test.concurrent/.classpath
- openjdk.test.debugging/.classpath
- openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/stf/hcrAgent/HCRLateAttachWorkload.java
- openjdk.test.gc/.classpath
- openjdk.test.jck/.classpath
- openjdk.test.jck/build.xml
- openjdk.test.jck/docs/README.md
- openjdk.test.jlm/.classpath
- openjdk.test.lambdasAndStreams/.classpath
- openjdk.test.lang/.classpath
- openjdk.test.load/.classpath
- openjdk.test.math/.classpath
- openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/ExplMod.java
- openjdk.test.nio/.classpath
- openjdk.test.serialization/.classpath
- openjdk.test.util/.classpath
- Removes version number from all prereq jar references in openjdk-systemtest repo
- Related to : https://github.com/AdoptOpenJDK/stf/issues/98
> Remove hard-coded version numbers from prereq jar references

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Each test's timeout limit is multiplied by the time factor value. One base time limit is 10 minutes, increase it to 20 minutes.
This is reflected by the `timeoutSeconds` value within `jtr` file.
Note: there were individual tests take slightly more than 10 min to finish in certain `ppc64le_linux` machines. Verified with this PR, the test in question passes in 10x grinder.
> Increase individual test timeout from 10 min to 20 min

- openjdk.test.debugging/build.xml
- openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/StringTransformer.java
- openjdk.test.debugging/src_110/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/MyClassVisitor.java
- openjdk.test.debugging/src_110/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/MyMethodVisitor.java
- openjdk.test.debugging/src_80/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/MyClassVisitor.java
- openjdk.test.debugging/src_80/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/MyMethodVisitor.java
- Change asm to jvm asm
- Set different Opcodes.ASM versions for jdk 8 and 11+
- Related Issue: https://github.com/eclipse/openj9/issues/11642
- Need to merge with PR (https://github.com/AdoptOpenJDK/openjdk-tests/pull/2182) together.
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>
> Fix HCRLateAttachWorkload_previewEnabled failure on jdk17

- openjdk.build/makefile
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/ClassloadingLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/ConcurrentLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/DirectByteBufferLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/LambdaLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/LangLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MathLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveMultiThrdLoad.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveMultiThrdLoadTrc.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleInvocLoad.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleThrdLoad.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MauveSingleThrdLoadTrc.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MixedLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/NioLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/SerializationLoadTest.java
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/UtilLoadTest.java
- Add time-based execution mechanism in STF load tests
- Related to https://github.com/AdoptOpenJDK/openjdk-tests/issues/2104
> Enable time-based load test mechanism in openjdk-systemtest load tests

- openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml
- openjdk.test.load/config/inventories/lambdasAndStreams/parallelStreams.xml
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/ParallelStreamsLoadTest.java
> Move TestParallelStreamOperations to its own workload

- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/remote/ClassProfiler.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/remote/MemoryProfiler.java
- openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/remote/ThreadProfiler.java
> Add stack trace print for jlm test connect exceptions

- openjdk.build/makefile
- Adds  time-based test targets to openjdk.systemtest make layer
- Removes Ant version numbers from openjdk.systemtest make layer (missed by https://github.com/AdoptOpenJDK/stf/issues/98) 
- Related PR https://github.com/eclipse/openj9-systemtest/pull/126
- Related issue https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/407
> Add time-based test targets in openjdk-systemtest make layer

- openjdk.test.concurrent/src/test.concurrent/net/adoptopenjdk/test/concurrent/jsr166y/ForkJoinPoolTest.java
> Exclude test for getActiveThreadCount in ForkJoinPoolTest.java

- openjdk.test.jck/build.xml
- openjdk.test.jck/src/native/makefile
- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
- openjdk.test.modularity/build.xml
- openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/JlinkPluginTest.java
- openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/JlinkTest.java
- openjdk.test.modularity/src/tests/com.test.jlink/native/makefile
- Remove dependency of systemtest native makefiles on on PLATFORM variable 
- Use uname commands to figure out platforms and platforms specific compiler settings 
- Reduce unnecessary platform-specific compiler flags
Related to  : https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/413
Related PR : https://github.com/eclipse/openj9-systemtest/pull/128
> Simplify native systemtest makefiles

- openjdk.test.jck/src/native/makefile
In JCK8, we do not have a "linux" folder under jni include, unlike the later JCK versions. Hence, for JCK8 AIX, we need to supply the "unix" folder in the include path for compiler to figure out necessary header files.
Resolves  backlog/issues/475
> Add unix include path for AIX for JCK8

- openjdk.test.math/src/test.math/net/adoptopenjdk/test/math/MathAPITest.java
- openjdk.test.math/src/test.math/net/adoptopenjdk/test/math/MathAPITestGenerator.java
Problem has been fixed: https://bugs.openjdk.java.net/browse/JDK-8255368.
Resolves https://github.com/AdoptOpenJDK/openjdk-tests/issues/2062.
> Re-enable exp() tests on x86

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Resolves backlog/issues/494 
Increase of timeout is related to backlog/issues/487  
> Launch RMI and RMID only for tests that need them + increase timeout

- openjdk.test.load/config/inventories/mauve/mauve_all.xml
- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
- openjdk.test.load/config/inventories/util/util_exclude.xml
This PR does the following: 
1) Disable `gnu.testlet.java.io.InputStreamReader.utf8` on all variants of mauve tests (ref: https://github.com/eclipse-openj9/openj9/issues/12830) 
2) Update issue links to adoptium in comments in mauve configuration XML files (these few files were missed in https://github.com/adoptium/aqa-systemtest/pull/425/)
Signed-off-by: Mesbah-Alam <Mesbah_Alam@ca.ibm.com>
> Disable InputStreamReader.utf8 + update references for adoptium in Mauve configuration files

- openjdk.test.jck/src/native/makefile
Currently, the native libs on Solaris are being compiled in 32bit rather than 64bit. This PR add's the `-m64` flag to force the compiler to use 64bit.
fixes:
```bash
wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
```
> force natives to be compiled in 64bit on solaris

- openjdk.test.jck/src/native/makefile
`jckjni_md.h` is actually located in the Solaris directory but is needed on Linux as well
I removed this as part of https://github.com/adoptium/aqa-systemtest/pull/430
> Re-introduce SOLARIS_PATH for linux TCK compilation

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
Excluding a failing test until its fix propagates into the right
repositories upstream. Right now they're in JDKx-dev, and we need
them in JDKx. We expect this to happen over the next few weeks,
possibly after the quarterly updates.
Signed-off-by: Adam Farley <adfarley@redhat.com>
> Excluding StringIndexOutOfBoundsException.constructor

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Increase stf timeout to handle some testcases that take longer than the standard 10min timeout.
> Increase stf jck timeout factor to x4

- openjdk.test.mauve/build.xml
For the [issue](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2483), removed the reference of check-for-download tool to remove system dependency.
Fixes https://github.com/AdoptOpenJDK/openjdk-tests/issues/2483
> Removed reference to check-for-download

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Add xWindows setting to allow java_io and signaturetest to run on mac, but don't set on Windows
> Allow java_io and signaturetest to run with no display on Mac

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
The xjc.sh script is based on ksh minumum syntax and as such will not work with standard "sh".
This PR mandates the use of bash on linux platforms.
The javatest framework launches the scripts via a Java ProcessCommand and as such will not use a shell.
> Enforce using bash for jck schema scripts on linux

- openjdk.test.jck/src/native/makefile
I'd be ok if we decided to switch to using `xlc` from the PATH, but the natives are currently trying to reference a nonexistant `linux` directory. I believe `amd64` will be ok for this as a default directory to use, but we'll see how well the latest test run goes. It could probably use a bit of a subsequent variable name refactor since using `OSX_PATH` on AIX is rather odd ...
We may wish to check this with anyone else utilising this part of the `aqa-systemtest` repository.
Signed-off-by: Stewart X Addison <sxa@redhat.com>
> Update AIX parameters in TCK makefile to allow native builds

- openjdk.test.jck/src/native/makefile
Bits of the TCK seem to be expecting this to be `.so` instead of `.a`
Signed-off-by: Stewart X Addison <sxa@redhat.com>
> Use .so instead of .a for AIX shlib extension in JCK natives

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
This previous fix for JCK11 does not apply to JCK8 as OsHelper class is jck11+ only: https://github.com/adoptium/aqa-systemtest/commit/af676759f9365f29533837b466bb1a38a92be4db
Added condition to only use workaround for jck11+.
> Change JCK8 AIX to use cmdAsString rather than cmdAsFile

- openjdk.test.jck/src/native/makefile
Fixes an issue building the TCK material
Signed-off-by: Stewart X Addison <sxa@redhat.com>
> Update JCK Natives compile flags to define _AMD64_ on Windows

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
Equivalent to https://github.com/adoptium/aqa-systemtest/pull/439/files for Solaris to enable TCK execution
Signed-off-by: Stewart X Addison <sxa@redhat.com>
> Run xjcCmd through ksh on Solaris

- openjdk.test.jck/config/default/jcktest.properties
On windows, we have been fudging the DNS records to use an internal IP which has resulted in the testhostname tests failing.
This PR switches the host to be trss instead
> Change testhost1name to be trss rather than jckservices

- openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/ClassHog.java
- openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/ClassMapHog.java
Resolves https://github.com/eclipse-openj9/openj9/issues/13325
Signed-off-by: Mesbah-Alam <Mesbah_Alam@ca.ibm.com>
> Avoid loading classes from RMI Activation package from JDK17+

- openjdk.test.load/config/inventories/concurrent/concurrent_exclude.xml
Disable `ForkJoinTaskTest` failed at both OpenJ9 & RI [1] 
To be enabled after fixing OpenJDK.
Note: Attempted to only comment out https://github.com/adoptium/aqa-systemtest/blob/09144b01e8025a6ee44cb8ac05a81df30319c403/openjdk.test.concurrent/src/test.concurrent/net/adoptopenjdk/test/concurrent/jsr166y/ForkJoinTaskTest.java#L174
But got another intermittent failure.
```
12:34:21  LT  testStarted : testAPI(net.adoptopenjdk.test.concurrent.jsr166y.ForkJoinTaskTest)
12:34:21  LT  testFailure: testAPI(net.adoptopenjdk.test.concurrent.jsr166y.ForkJoinTaskTest): 29 : getMySurplusQueuedTaskCount() expected:<0> but was:<-8>
12:34:21  LT  junit.framework.AssertionFailedError: 29 : getMySurplusQueuedTaskCount() expected:<0> but was:<-8>
12:34:21  LT  	at junit.framework.Assert.fail(Assert.java:57) …
```
> Disable ForkJoinTaskTest failed at both OpenJ9 & RI

- openjdk.test.jck/src/native/makefile
fixes failing `vm_jni` tests on macOS arm64. The `-arch arm64` flag is needed because the shell runs in x86_64 emulation
> Add support for compiling natives on macOS arm64

- openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java
RMID has been removed as per [JEP 407](https://openjdk.java.net/jeps/407), and should not be used.
This code has been tested against jdk17, and successfully prevents us from calling rmid.
Signed-off-by: Adam Farley <adfarley@redhat.com>
> Exclude rmid references for jdk17 and up.

- openjdk.test.jck/src/native/makefile
Specify -Wc,lp64 -Wl,lp64 in native compilation flags for tck on z/OS. 
Resolves : backlog/issues/595 
Signed-off-by: Mesbah-Alam <Mesbah_Alam@ca.ibm.com>
> Specify -Wc,lp64 -Wl,lp64 in native compilation flags for tck on z/OS

- openjdk.build/docs/build.md
It's not at the top level, but in the `stf.core/scripts` folder.
> Correct path to stf.pl in build document

- openjdk.test.lambdasAndStreams/src/test.lambda/net/adoptopenjdk/test/lambda/support/Person.java
A lock on the Person class must now be acquired before incrementing
nextSerialNumber. This prevents conflicting updates when multiple threads try
to increment it at the same time.
Signed-off-by: jimmyk <jimmyk@ca.ibm.com>
> Add synchronization to Person class

- openjdk.test.load/config/inventories/mix/mix-more-zos.xml
- openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MixedLoadTest.java
In order to avoid running into encoding issues that the generated class files of NIO load test pose (see openj9-openjdk-jdk11-zos/issues/342 for details), while on z/OS we will run a mixed load test that does not include Nio load tests. 
This PR creates a new inventory file to be used by MixedLoadTest while on z/OS which essentially uses the same loads as before minus NIO tests. 
Signed-off-by: Mesbah-Alam <Mesbah_Alam@ca.ibm.com>
> Exclude nio from zos

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
This test should now run and pass on all JDK versions it's meant to
run against, as the upstream OpenJDK bug (JDK-8267773) is resolved
and backported, with the code fully propagated.
Signed-off-by: Adam Farley <adfarley@redhat.com>
> Reintroducing StringIndexOutOfBoundsException as the bug is fixed

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- Exclude `gnu.testlet.java.lang.ThreadDeath.classInfo.isAnnotationPresent ` from Mauve load as it doesn't work on JDK-20. 
- Resolves : https://github.com/eclipse-openj9/openj9-systemtest/issues/147
FYI @Peter_Shipton@ca.ibm.com
> Exclude isAnnotationPresent from mauve load for jdk20

- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
This is the equivalent exclude for https://github.com/adoptium/aqa-systemtest/pull/480
Related https://github.com/adoptium/aqa-tests/issues/4341
Signed-off-by: Mesbah Alam [Mesbah_Alam@ca.ibm.com](mailto:Mesbah_Alam@ca.ibm.com)
> Exclude isAnnotationPresent from multithreaded mauve load

- openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/ClassHog.java
- openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/ClassMapHog.java
Fixes https://github.com/adoptium/aqa-tests/issues/4732
java.lang.Compiler was removed in JDK 21:
https://bugs.openjdk.org/browse/JDK-8205129
https://jdk.java.net/21/release-notes
Also has some spacing fixes nearby.
> Exclude java.lang.Compiler from classloading test on JDK 21+

- openjdk.test.jck/src/native/makefile
- Fixes adoptium/aqa-systemtest#491
> Change xlc to be found on the PATH and not a specific version

- openjdk.test.mauve/build.xml
Reverts adoptium/aqa-systemtest#489
related: https://github.com/adoptium/aqa-tests/issues/5760#issuecomment-2491232607
> Revert "Build the tests with release=8 whenever it is possible"

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
The SecurityManager is removed in JDK 24. Exclude Mauve tests that are failing due to illegal use of the security manager.
> Exclude Mauve tests that use SecurityManager for JDK24

- openjdk.test.load/config/inventories/mauve/mauve_all_exclude.xml
- openjdk.test.load/config/inventories/mauve/mauve_multiThread_exclude.xml
java.lang.Package.classInfo.getModifiers
java.text.DecimalFormat.setNegativePrefix/Suffix
java.text.DecimalFormat.setPositivePrefix/Suffix
These tests are invalid as of jdk25.
Closes https://github.com/eclipse-openj9/openj9/issues/21729
Tested via https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/4441/
> Exclude mauve Package getModifiers, DecimalFormat suffix/prefix
